platform :ios, '11.0'

target 'savedTech' do
  
  use_frameworks!

  # add pods for desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Core'
  pod 'Firebase/Storage'

end
